### ISSUE TITLE
Error in workflow mapping

### ISSUE THREAD

**Issue by sallesmath** [faircloth-lab/phyluce#271]
Hello!

This has been discussed previously and I've read those posts , but I'm still having the following error:

```
(phyluce-1.7.1) sallesmath@DESKTOP-NQCD32J:~/dados_uce/phyluce_dados_uce_tropidurus/mapping$ phyluce_workflow --config config.yaml --output results_mapping --workflow mapping --cores 4
[WARNING] Output directory exists, REMOVE [y/n]: y
Building DAG of jobs...
MissingInputException in line 39 of /home/sallesmath/anaconda3/envs/phyluce-1.7.1/phyluce/workflows/mapping/Snakefile:
Missing input files for rule copy_and_build_index:
/home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/amcc-204349.contigs.fasta
```
This is my config.yaml file:
```
reads:
    amcc-204349: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-amcc/amcc-204349/
    amcc-204498: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-amcc/amcc-204498/
    amcc-204357: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-amcc/amcc-204357/
    amcc-204384: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-amcc/amcc-204384/
    amcc-204510: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-amcc/amcc-204510/
    chunb-74137: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-chunb/chunb-74137/
    chunb-74145: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-chunb/chunb-74145/
    chunb-74146: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-chunb/chunb-74146/
    chunb-74147: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-chunb/chunb-74147/
    chunb-74155: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-chunb/chunb-74155/
    chunb-74156: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-chunb/chunb-74156/
    chunb-74157: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-chunb/chunb-74157/
    chunb-74163: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-chunb/chunb-74163/
    chunb-74162: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-chunb/chunb-74162/
    lg-15512987: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-lg/lg-15512987/
    mtr-29592: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-mtr/mtr-29592/
    mtr-29503: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-mtr/mtr-29503/
    mtr-29622: /home/dados_uce/phyluce_dados_uce_tropidurus/raw-fastq/raw-fastq-mtr/mtr-29622/

contigs:
    amcc-204349: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/amcc-204349.contigs.fasta
    amcc-204498: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/amcc-204498.contigs.fasta
    amcc-204357: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/amcc-204357.contigs.fasta
    amcc-204384: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/amcc-204384.contigs.fasta
    amcc-204510: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/amcc-204510.contigs.fasta
    chunb-74137: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/chunb-74137.contigs.fasta
    chunb-74145: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/chunb-74145.contigs.fasta
    chunb-74146: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/chunb-74146.contigs.fasta
    chunb-74147: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/chunb-74147.contigs.fasta
    chunb-74155: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/chunb-74155.contigs.fasta
    chunb-74156: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/chunb-74156.contigs.fasta
    chunb-74157: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/chunb-74157.contigs.fasta
    chunb-74163: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/chunb-74163.contigs.fasta
    chunb-74162: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/chunb-74162.contigs.fasta
    lg-15512987: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/lg-15512987.contigs.fasta
    mtr-29592: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/mtr-29592.contigs.fasta
    mtr-29503: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/mtr-29503.contigs.fasta
    mtr-29622: /home/dados_uce/phyluce_dados_uce_tropidurus/spades-assemblies/contigs/mtr-29622.contigs.fasta
```
I've already tried checking the configuration file several times, renamed the sequence files, changed the configuration of r1 and r2_pattern, but nothing worked.

Do you have any idea as to what might be going on?

Thanks!
